# --------------------------------------------------------------------------------------------------------------------                                                                                                                                                                                #*eddiere
services:
  # 1. Grafana Dashboard Web Service (Free Tier)
  - type: web
    name: grafana-monitoring-ui
    env: docker
    dockerfilePath: ./Dockerfile.grafana
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 3000
      - key: GF_SECURITY_ADMIN_PASSWORD
        generateValue: true
      - key: GF_USERS_ALLOW_SIGN_UP
        value: "false"

  # 2. Prometheus Metrics Collector (Free Tier Web Service)
  - type: web
    name: prometheus-time-series-db
    env: docker
    dockerfilePath: ./Dockerfile.prometheus
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 9090
