# --------------------------------------------------------------------------------------------------------------------                                                                                                                                                                                #*eddiere
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: Google Cloud Monitoring (CyberAwareness)
    type: stackdriver
    access: proxy
    jsonData:
      authenticationType: gce
      defaultProject: greencandlecyberawareness
    editable: true

